url: "https://www.viva-downloader.nl" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Forum draadjes downloader" # the name of your site, e.g. ACME Corp.
